<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
	This stylesheets automatically generates the file antspec.xml based on
	the file antschema.xml
-->
<xsl:stylesheet	version="1.0"
				xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                >

<xsl:variable name="tasks" select="/schema/element[@name='target']/allowedsubelements/@names"/>

<xsl:template match="schema">
	<displayspec>

		<xsl:comment>
			This file was automatically generated by antschema2antspec.xsl.
		</xsl:comment>

		<xsl:apply-templates/>
	</displayspec>
</xsl:template>

<xsl:template match="element">
	<element name="{@name}">
		<showattributes>
			<xsl:attribute name="names">
				<xsl:for-each select="attributes/attribute">
					<xsl:choose>
						<xsl:when  test="position()=last()"><xsl:value-of select="@name"/></xsl:when>
						<xsl:otherwise><xsl:value-of select="@name"/>,</xsl:otherwise>
					</xsl:choose>
				</xsl:for-each>
			</xsl:attribute>
		</showattributes>
		<display type="block"/>
		<xsl:choose>
			<xsl:when test="@name='project'">
				<background-color red="224" green="238" blue="224"/>
			</xsl:when>
			<xsl:when test="@name='target'">
				<background-color red="255" green="157" blue="112"/>
			</xsl:when>
			<!-- if it is a deprecated task -->
			<xsl:when test="@name='copydir' or @name='copyfile' or @name='rename' or @name='javadoc2'">
				<background-color red="255" green="96" blue="38"/>
			</xsl:when>
			<!-- if it is a task (why does ends-with() not exist?)-->
			<xsl:when test="contains($tasks, concat(',',@name,',')) or contains($tasks, concat(@name,','))">
				<background-color red="138" green="234" blue="218"/>
			</xsl:when>
			<!-- otherwise -->
			<xsl:otherwise>
				<background-color red="226" green="208" blue="208"/>
			</xsl:otherwise>
		</xsl:choose>
	</element>
</xsl:template>

</xsl:stylesheet>
